### ISSUE TITLE
[PoC] Provide proposedObjectiveValue on submitSolution

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#248] opened 2019-10-30 10:02 UTC
For the purpose of gas savings, it would be efficient if the contract would compare the `currentWinningObjectiveValue` with the `proposedObjectiveValue`. This would avoid a bunch of unnecessary computation if the transaction is going to fail anyway.

In brief, contract should abort verification early if claimed value is not higher than current one (could be due to a race condition when submitting competing solutions).

**Comment by fleupold** [comment] 2019-10-30 13:18
Duplicate of #221

**Closed as completed by fleupold** 2019-10-30 13:18 UTC
